# Generated by Django 5.1.3 on 2024-11-24 01:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HeartGuard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Informe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('age', models.IntegerField()),
                ('sex', models.IntegerField(choices=[(0, 'Mujer'), (1, 'Hombre')])),
                ('cp', models.IntegerField()),
                ('trtbps', models.IntegerField()),
                ('chol', models.IntegerField()),
                ('fbs', models.IntegerField(choices=[(0, 'Falso'), (1, 'Verdadero')])),
                ('restecg', models.IntegerField()),
                ('thalachh', models.IntegerField()),
                ('exng', models.IntegerField(choices=[(0, 'No'), (1, 'Sí')])),
                ('oldpeak', models.FloatField()),
                ('slp', models.IntegerField()),
                ('caa', models.IntegerField()),
                ('thall', models.IntegerField()),
                ('output', models.IntegerField(choices=[(0, 'Enfermedad ausente'), (1, 'Enfermedad presente')])),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='informes', to='HeartGuard.paciente')),
            ],
        ),
    ]
