# Generated by Django 5.1.3 on 2024-11-24 02:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HeartGuard', '0002_informe'),
    ]

    operations = [
        migrations.RenameField(
            model_name='informe',
            old_name='fecha_creacion',
            new_name='fecha',
        ),
        migrations.AddField(
            model_name='informe',
            name='medico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='informes', to='HeartGuard.medico'),
        ),
        migrations.AddField(
            model_name='medico',
            name='ciudad',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='medico',
            name='departamento',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='medico',
            name='direccion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medico',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='ciudad',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='departamento',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='informe',
            name='age',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='informe',
            name='caa',
            field=models.IntegerField(verbose_name='Número de Vasos Principales Coloreados'),
        ),
        migrations.AlterField(
            model_name='informe',
            name='chol',
            field=models.PositiveIntegerField(verbose_name='Colesterol Sérico (mg/dl)'),
        ),
        migrations.AlterField(
            model_name='informe',
            name='cp',
            field=models.IntegerField(verbose_name='Tipo de Dolor en el Pecho'),
        ),
        migrations.AlterField(
            model_name='informe',
            name='exng',
            field=models.BooleanField(verbose_name='Angina Inducida por Ejercicio'),
        ),
        migrations.AlterField(
            model_name='informe',
            name='fbs',
            field=models.BooleanField(verbose_name='Azúcar en Sangre en Ayunas > 120 mg/dl'),
        ),
        migrations.AlterField(
            model_name='informe',
            name='oldpeak',
            field=models.FloatField(verbose_name='Depresión ST'),
        ),
        migrations.AlterField(
            model_name='informe',
            name='output',
            field=models.IntegerField(choices=[(0, 'Enfermedad Ausente'), (1, 'Enfermedad Presente')]),
        ),
        migrations.AlterField(
            model_name='informe',
            name='restecg',
            field=models.IntegerField(verbose_name='Resultados del Electrocardiograma en Reposo'),
        ),
        migrations.AlterField(
            model_name='informe',
            name='slp',
            field=models.IntegerField(verbose_name='Pendiente del Segmento ST'),
        ),
        migrations.AlterField(
            model_name='informe',
            name='thalachh',
            field=models.PositiveIntegerField(verbose_name='Frecuencia Cardíaca Máxima Alcanzada'),
        ),
        migrations.AlterField(
            model_name='informe',
            name='thall',
            field=models.IntegerField(verbose_name='Tipo de Talasemia'),
        ),
        migrations.AlterField(
            model_name='informe',
            name='trtbps',
            field=models.PositiveIntegerField(verbose_name='Presión Arterial en Reposo (mm Hg)'),
        ),
    ]
