# Generated by Django 5.1.3 on 2024-11-24 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HeartGuard', '0005_informe_observaciones'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medico',
            old_name='apellido',
            new_name='apellidos',
        ),
        migrations.RenameField(
            model_name='medico',
            old_name='nombre',
            new_name='nombres',
        ),
        migrations.AddField(
            model_name='medico',
            name='tipo_documento',
            field=models.CharField(choices=[('CC', 'Cédula de Ciudadanía'), ('TI', 'Tarjeta de Identidad'), ('PA', 'Pasaporte')], default='CC', max_length=3),
        ),
        migrations.AddField(
            model_name='paciente',
            name='apellidos',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
