# Generated by Django 5.1.3 on 2024-11-24 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HeartGuard', '0006_rename_apellido_medico_apellidos_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paciente',
            old_name='nombre',
            new_name='nombres',
        ),
    ]
