# Generated by Django 5.1.3 on 2024-11-30 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HeartGuard', '0009_notificacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='informe',
            name='documento',
            field=models.CharField(default=1, max_length=20, verbose_name='Documento del Paciente'),
            preserve_default=False,
        ),
    ]
