# Generated by Django 5.1.3 on 2024-12-01 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HeartGuard', '0010_informe_documento'),
    ]

    operations = [
        migrations.AddField(
            model_name='informe',
            name='is_used_for_training',
            field=models.BooleanField(default=False, verbose_name='Usado para Reentrenar'),
        ),
    ]
