# Generated by Django 5.1.3 on 2024-12-03 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HeartGuard', '0011_informe_is_used_for_training'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informe',
            name='output',
            field=models.IntegerField(blank=True, choices=[(0, 'Enfermedad Ausente'), (1, 'Enfermedad Presente')], null=True),
        ),
    ]
